### ISSUE TITLE
ReferenceError: URL is not defined

### ISSUE THREAD

**Issue by matiaspl** [warren-bank/node-hls-downloader#2]
hlsdl v4.0.0, node v5.0.2
Regardless of the selected url after selecting the stream number I get the following:

ReferenceError: URL is not defined
    at resolve_relative_url (/usr/local/lib/node_modules/@warren-bank/node-hls-downloader/bin/hls-downloader.js:271:16)
    at Promise (/usr/local/lib/node_modules/@warren-bank/node-hls-downloader/bin/hls-downloader.js:216:15)
    at new Promise (<anonymous>)
    at get_media_streams (/usr/local/lib/node_modules/@warren-bank/node-hls-downloader/bin/hls-downloader.js:182:10)
    at get_subtitle_streams (/usr/local/lib/node_modules/@warren-bank/node-hls-downloader/bin/hls-downloader.js:267:10)
    at process_stream (/usr/local/lib/node_modules/@warren-bank/node-hls-downloader/bin/hls-downloader.js:432:9)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)

**Comment by warren-bank** [comment]
https://github.com/warren-bank/node-hls-downloader#requirements
